import Foundation

enum SkillEffectType: String, CaseIterable, Sendable, Hashable {
    case absorption
    case actionOrderMultiplier
    case actionOrderShuffle
    case attackCountAdditive
    case attackCountMultiplier
    case additionalDamageAdditive
    case additionalDamageMultiplier
    case antiHealing
    case autoDegradationRepair
    case barrier
    case barrierOnGuard
    case berserk
    case breathVariant
    case counterAttackEvasionMultiplier
    case criticalDamageMultiplier
    case criticalDamagePercent
    case criticalDamageTakenMultiplier
    case criticalRateAdditive
    case criticalRateCap
    case criticalRateMaxAbsolute
    case criticalRateMaxDelta
    case damageDealtMultiplier
    case damageDealtMultiplierAgainst
    case damageDealtPercent
    case damageTakenMultiplier
    case damageTakenPercent
    case degradationRepair
    case degradationRepairBoost
    case growthMultiplier
    case dodgeCap
    case endOfTurnHealing
    case endOfTurnSelfHPPercent
    case equipmentSlotAdditive
    case equipmentSlotMultiplier
    case equipmentStatMultiplier
    case explorationTimeMultiplier
    case extraAction
    case martialBonusMultiplier
    case martialBonusPercent
    case minHitScale
    case partyAttackFlag
    case partyAttackTarget
    case parry
    case penetrationDamageTakenMultiplier
    case procMultiplier
    case procRate
    case reaction
    case reactionNextTurn
    case resurrectionActive
    case resurrectionBuff
    case resurrectionPassive
    case resurrectionSave
    case resurrectionSummon
    case resurrectionVitalize
    case retreatAtTurn
    case rewardExperienceMultiplier
    case rewardExperiencePercent
    case rewardGoldMultiplier
    case rewardGoldPercent
    case rewardItemMultiplier
    case rewardItemPercent
    case rewardTitleMultiplier
    case rewardTitlePercent
    case rowProfile
    case statAdditive
    case statConversionLinear
    case statConversionPercent
    case statFixedToOne
    case statMultiplier
    case runawayDamage
    case runawayMagic
    case sacrificeRite
    case talentStat
    case incompetenceStat
    case itemStatMultiplier
    case shieldBlock
    case specialAttack
    case spellAccess
    case spellCharges
    case spellPowerMultiplier
    case spellPowerPercent
    case spellSpecificMultiplier
    case spellSpecificTakenMultiplier
    case spellTierUnlock
    case statusInflict
    case statusResistanceMultiplier
    case statusResistancePercent
    case tacticSpellAmplify
    case targetingWeight
    case coverRowsBehind
    case magicNullifyChancePercent
    case magicCriticalChancePercent
    case timedBreathPowerAmplify
    case timedBuffTrigger
    case timedMagicPowerAmplify
}
