// ==============================================================================
// SkillEffectFamily.swift
// Epika
// ==============================================================================
//
// 【責務】
//   - スキルエフェクトファミリーID（skill_effect_families.id）の管理
//   - 378エントリのファミリーをUInt16 enumとして定義
//   - 文字列識別子との相互変換をサポート
//
// 【データ構造】
//   - SkillEffectFamily: スキルエフェクトファミリーを表すenum（UInt16）
//   - identifierMap: 文字列識別子からファミリーへのマッピング
//   - reverseMap: ファミリーから文字列識別子へのマッピング
//
// 【使用箇所】
//   - スキルエフェクトのグループ化・識別
//   - ペイロードのfamilyId解決
//
// ==============================================================================

import Foundation

/// スキルエフェクトファミリーID（skill_effect_families.id）
/// 378エントリ、UInt16で管理
enum SkillEffectFamily: UInt16, CaseIterable, Sendable, Hashable {
    case absentStat = 1
    case absorptionGeneral = 2
    case actionOrderShuffle = 3
    case actionOrderMultiplierGeneral = 4
    case additionalDamageScoreAdditive = 5
    case additionalDamageScoreMultiplier = 6
    case antiHealingGeneral = 7
    case attackCountAdditive = 8
    case attackCountMultiplier = 9
    case autoDegradationRepairGeneral = 10
    case berserkTrigger = 11
    case breathPower = 12
    case breathVariant = 13
    case counterAttackEvasionMultiplierGeneral = 14
    case criticalDamageMultiplier = 15
    case criticalDamagePercent = 16
    case criticalDamageTakenMultiplierGeneral = 17
    case criticalChancePercentAdd = 18
    case criticalChancePercentCap = 19
    case criticalChancePercentMax = 20
    case criticalChancePercentMaxDelta = 21
    case damageDealtMultiplierBreath = 22
    case damageDealtMultiplierMagical = 23
    case damageDealtMultiplierPhysical = 24
    case damageDealtMultiplierAgainstDivine = 25
    case damageDealtMultiplierAgainstDragon = 26
    case damageDealtMultiplierAgainstHumanoid = 27
    case damageDealtMultiplierAgainstMonster = 28
    case damageDealtMultiplierAgainstUndead = 29
    case damageDealtPercentBreath = 30
    case damageDealtPercentMagical = 31
    case damageDealtPercentPhysical = 32
    case damageTakenMultiplierBreath = 33
    case damageTakenMultiplierMagical = 34
    case damageTakenMultiplierPhysical = 35
    case damageTakenPercentBreath = 36
    case damageTakenPercentMagical = 37
    case damageTakenPercentPhysical = 38
    case degradationRepairGeneral = 39
    case degradationRepairBoostGeneral = 40
    case dodgeCapGeneral = 41
    case endOfTurnHealingParty = 42
    case endOfTurnSelfHPDamage = 43
    case endOfTurnSelfHPHeal = 44
    case equipmentSlotsAdditive = 45
    case equipmentSlotsMultiplier = 46
    case equipmentStatMultiplierArmor = 47
    case equipmentStatMultiplierBow = 48
    case equipmentStatMultiplierForSynthesis = 49
    case equipmentStatMultiplierGauntlet = 50
    case equipmentStatMultiplierGem = 51
    case equipmentStatMultiplierGrimoire = 52
    case equipmentStatMultiplierHeavyArmor = 53
    case equipmentStatMultiplierKatana = 54
    case equipmentStatMultiplierMazoMaterial = 55
    case equipmentStatMultiplierOther = 56
    case equipmentStatMultiplierRaceSpecific = 57
    case equipmentStatMultiplierRobe = 58
    case equipmentStatMultiplierRod = 59
    case equipmentStatMultiplierShield = 60
    case equipmentStatMultiplierSword = 61
    case equipmentStatMultiplierThinSword = 62
    case equipmentStatMultiplierWand = 63
    case explorationTimeMultiplierBabel = 64
    case explorationTimeMultiplierGeneral = 65
    case extraActionGeneral = 66
    case growthMultiplierGeneral = 67
    case incompetenceStat = 68
    case itemStatMultiplierCriticalChancePercent = 69
    case itemStatMultiplierEvasionScore = 70
    case itemStatMultiplierHitScore = 71
    case itemStatMultiplierMagicalAttackScore = 72
    case itemStatMultiplierMagicalDefenseScore = 73
    case itemStatMultiplierMagicalHealingScore = 74
    case itemStatMultiplierMaxHP = 75
    case itemStatMultiplierPhysicalAttackScore = 76
    case itemStatMultiplierPhysicalDefenseScore = 77
    case itemStatMultiplierTrapRemovalScore = 78
    case jobAssassinAccuracy = 79
    case jobAssassinCritDamage = 80
    case jobAssassinLethalBlow = 81
    case jobAssassinMasterAssassin = 82
    case jobAssassinWeakPointStrike = 83
    case jobBlademasterAccuracy = 84
    case jobBlademasterMaster = 85
    case jobBlademasterPeerless = 86
    case jobBlademasterPhysPower = 87
    case jobBlademasterTechnique = 88
    case jobHunterAccuracy = 89
    case jobHunterBowMastery = 90
    case jobHunterPierce = 91
    case jobHunterPrecision = 92
    case jobHunterVolley = 93
    case jobJesterAllStats = 94
    case jobJesterConfusion = 95
    case jobJesterGrandFinale = 96
    case jobJesterLuck = 97
    case jobJesterMischief = 98
    case jobLordCommand = 99
    case jobLordControl = 100
    case jobLordLeadership = 101
    case jobLordPartyPhys = 102
    case jobLordRally = 103
    case jobMageAbsorb = 104
    case jobMageAmplify = 105
    case jobMageDestroy = 106
    case jobMageMagicPower = 107
    case jobMageWisdom = 108
    case jobMonkEnlighten = 109
    case jobMonkMagicResist = 110
    case jobMonkMeditate = 111
    case jobMonkSpirit = 112
    case jobMonkWard = 113
    case jobNinjaCriticalChancePercent = 114
    case jobNinjaDeathblow = 115
    case jobNinjaEvasion = 116
    case jobNinjaShadowClone = 117
    case jobNinjaStealth = 118
    case jobPriestBlessing = 119
    case jobPriestHealBonus = 120
    case jobPriestMagicResist = 121
    case jobPriestProtect = 122
    case jobPriestSalvation = 123
    case jobRoyallineAllStats = 124
    case jobRoyallineAura = 125
    case jobRoyallineDominion = 126
    case jobRoyallineGpBonus = 127
    case jobRoyallineMajesty = 128
    case jobSageHealBonus = 129
    case jobSageKnowledge = 130
    case jobSageMagicPower = 131
    case jobSageVersatile = 132
    case jobSageWisdom = 133
    case jobSamuraiCritDamage = 134
    case jobSamuraiIai = 135
    case jobSamuraiKatanaMastery = 136
    case jobSamuraiSlash = 137
    case jobSamuraiSpirit = 138
    case jobSpellbladeBladeMagic = 139
    case jobSpellbladeFusion = 140
    case jobSpellbladeMagicPower = 141
    case jobSpellbladeMagicSword = 142
    case jobSpellbladePhysPower = 143
    case jobSwordsmanCombo = 144
    case jobSwordsmanCounter = 145
    case jobSwordsmanFollowup = 146
    case jobSwordsmanMultiAttack = 147
    case jobSwordsmanPhysPower = 148
    case jobThiefCriticalChancePercent = 149
    case jobThiefDoubleAction = 150
    case jobThiefEvasion = 151
    case jobThiefFortune = 152
    case jobThiefSurvival = 153
    case jobWarriorArmament = 154
    case jobWarriorFortify = 155
    case jobWarriorGuardian = 156
    case jobWarriorMaxHP = 157
    case jobWarriorPhysResist = 158
    case martialBonusMultiplierMartial = 159
    case martialBonusPercentMartial = 160
    case masterAssassinLethal = 161
    case masterAssassinMastery = 162
    case masterAssassinWeakpoint = 163
    case masterBlademasterMaster = 164
    case masterBlademasterPeerless = 165
    case masterBlademasterTechnique = 166
    case masterHunterPierce = 167
    case masterHunterPrecision = 168
    case masterHunterVolley = 169
    case masterJesterConfusion = 170
    case masterJesterFinale = 171
    case masterJesterMischief = 172
    case masterLordCommand = 173
    case masterLordControl = 174
    case masterLordRally = 175
    case masterMageAbsorb = 176
    case masterMageAmplify = 177
    case masterMageDestroy = 178
    case masterMonkEnlighten = 179
    case masterMonkMeditate = 180
    case masterMonkWard = 181
    case masterNinjaDeathblow = 182
    case masterNinjaShadowClone = 183
    case masterNinjaStealth = 184
    case masterPriestBlessing = 185
    case masterPriestProtect = 186
    case masterPriestSalvation = 187
    case masterRoyallineAura = 188
    case masterRoyallineDominion = 189
    case masterRoyallineMajesty = 190
    case masterSageKnowledge = 191
    case masterSageVersatile = 192
    case masterSageWisdom = 193
    case masterSamuraiIai = 194
    case masterSamuraiSlash = 195
    case masterSamuraiSpirit = 196
    case masterSpellbladeBladeMagic = 197
    case masterSpellbladeFusion = 198
    case masterSpellbladeMagicSword = 199
    case masterSwordsmanCombo = 200
    case masterSwordsmanCounter = 201
    case masterSwordsmanFollowup = 202
    case masterThiefDoubleAction = 203
    case masterThiefFortune = 204
    case masterThiefSurvival = 205
    case masterWarriorArmament = 206
    case masterWarriorFortify = 207
    case masterWarriorGuardian = 208
    case parryGeneral = 209
    case partyAttackFlags = 210
    case partyAttackTargets = 211
    case penetrationDamageTakenMultiplierGeneral = 212
    case procMultiplierGeneral = 213
    case procRateAdditiveCounter = 214
    case procRateAdditiveCriticalCombo = 215
    case procRateAdditiveFightingSpirit = 216
    case procRateMultiplierBreathCounter = 217
    case procRateMultiplierCounter = 218
    case procRateMultiplierCrisisEvasion = 219
    case procRateMultiplierInstantResurrection = 220
    case procRateMultiplierMagicCounter = 221
    case procRateMultiplierMagicSupport = 222
    case procRateMultiplierManaDecomposition = 223
    case procRateMultiplierPursuit = 224
    case procRateMultiplierReattack = 225
    case procRateMultiplierReflectionRecovery = 226
    case raceAmazonessMagicDamagedCounter = 227
    case raceAmazonessTurnAttackCount = 228
    case raceCyborgCumulativeHit = 229
    case raceCyborgLateAction = 230
    case raceDarkelfAllyMagicReaction = 231
    case raceDarkelfKillReaction = 232
    case raceDragonnewtBreathCounter = 233
    case raceDragonnewtPreemptiveBreath = 234
    case raceDwarfCounterAttack = 235
    case raceDwarfEnemyDebuff = 236
    case raceElfAutoStatusCure = 237
    case raceElfMagicHealReaction = 238
    case raceGiantCoverAlly = 239
    case raceGiantTurnHealing = 240
    case raceGnomeMagicPower = 241
    case raceGnomeSpellRecovery = 242
    case raceHomunculusAdditionalDamageScore = 243
    case raceHomunculusAllStatBoost = 244
    case raceHomunculusEquipSlot = 245
    case raceHomunculusHealBonus = 246
    case raceHumanExpBonus = 247
    case raceHumanLevelDamageTaken = 248
    case raceHumanProcBoost = 249
    case raceHumanTurnBuff = 250
    case raceOniNoKillReaction = 251
    case raceOniTurnStatBuff = 252
    case racePsychicMagicCrit = 253
    case racePsychicMagicNullify = 254
    case racePygmychumBreathEvade = 255
    case racePygmychumCritDamage = 256
    case racePygmychumExtraAction = 257
    case raceTenguCounterPenalty = 258
    case raceTenguEvasionBoost = 259
    case raceTenguFirstTurnAction = 260
    case raceUndeadAutoResurrection = 261
    case raceUndeadDeathSave = 262
    case raceVampireMagicCounter = 263
    case raceVampireOpeningBuff = 264
    case raceWerecatCritCap = 265
    case raceWerecatFirstTurnHit = 266
    case raceWerecatTargeting = 267
    case reactionCounterAllyDamagedPhysical = 268
    case reactionCounterAllyDefeated = 269
    case reactionCounterSelfDamagedMagical = 270
    case reactionCounterSelfDamagedPhysical = 271
    case reactionCounterSelfEvadePhysical = 272
    case reactionNextTurnGeneral = 273
    case resurrectionActive = 274
    case resurrectionForced = 275
    case resurrectionInstant = 276
    case resurrectionNecromancer = 277
    case resurrectionSave = 278
    case resurrectionUndeath = 279
    case resurrectionVitalized = 280
    case retreatAtTurnGeneral = 281
    case rewardExperienceMultiplier = 282
    case rewardExperiencePercent = 283
    case rewardGoldMultiplier = 284
    case rewardGoldPercent = 285
    case rewardItemMultiplier = 286
    case rewardItemPercent = 287
    case rewardTitleMultiplier = 288
    case rewardTitlePercent = 289
    case rowProfileBalanced = 290
    case rowProfileNear = 291
    case rowProfileMixed = 292
    case rowProfileFar = 293
    case runawayDamage = 294
    case runawayMagic = 295
    case sacrificeRiteGeneral = 296
    case shieldBlockGeneral = 297
    case specialAttackSpecialA = 298
    case specialAttackSpecialB = 299
    case specialAttackSpecialC = 300
    case specialAttackSpecialD = 301
    case specialAttackSpecialE = 302
    case spellAccessMageForget = 303
    case spellAccessMageLearn = 304
    case spellAccessPriestForget = 305
    case spellAccessPriestLearn = 306
    case spellChargesTacticExtra = 307
    case spellChargesTriple = 308
    case spellPowerMultiplierGeneral = 309
    case spellPowerPercentGeneral = 310
    case spellSpecificMultiplierSpellMageBlizzard = 311
    case spellSpecificMultiplierSpellMageFireball = 312
    case spellSpecificMultiplierSpellMageMagicArrow = 313
    case spellSpecificMultiplierSpellMageNuclear = 314
    case spellSpecificMultiplierSpellMageThunderBolt = 315
    case spellSpecificMultiplierSpellPriestHeal = 316
    case spellSpecificMultiplierSpellPriestHealPlus = 317
    case spellSpecificMultiplierSpellPriestPartyHeal = 318
    case spellSpecificTakenMultiplierBlizzard = 319
    case spellSpecificTakenMultiplierFireball = 320
    case spellSpecificTakenMultiplierMagicArrow = 321
    case spellSpecificTakenMultiplierNuclear = 322
    case spellSpecificTakenMultiplierThunderBolt = 323
    case spellTierUnlockMage = 324
    case spellTierUnlockPriest = 325
    case statAdditiveEvasionScore = 326
    case statAdditiveHitScore = 327
    case statAdditiveMagicalAttackScore = 328
    case statAdditiveMagicalDefenseScore = 329
    case statAdditiveMagicalHealingScore = 330
    case statAdditivePhysicalAttackScore = 331
    case statAdditivePhysicalDefenseScore = 332
    case statConversionLinearAttackCountCriticalChancePercent = 333
    case statConversionLinearAttackCountEvasionScore = 334
    case statConversionLinearAttackCountMagicalAttackScore = 335
    case statConversionLinearAttackCountMagicalDefenseScore = 336
    case statConversionLinearAttackCountMagicalHealingScore = 337
    case statConversionLinearAttackCountPhysicalDefenseScore = 338
    case statConversionPercentMagicalAttackScoreHitScore = 339
    case statConversionPercentMagicalAttackScoreMaxHP = 340
    case statConversionPercentMagicalAttackScorePhysicalAttackScore = 341
    case statConversionPercentMagicalHealingScoreHitScore = 342
    case statConversionPercentMagicalHealingScoreMagicalAttackScore = 343
    case statConversionPercentMagicalHealingScoreMagicalDefenseScore = 344
    case statConversionPercentMagicalHealingScoreMaxHP = 345
    case statConversionPercentMagicalHealingScorePhysicalAttackScore = 346
    case statConversionPercentPhysicalAttackScoreMaxHP = 347
    case statConversionPercentPhysicalDefenseScoreAttackAndHit = 348
    case statConversionPercentPhysicalDefenseScoreMaxHP = 349
    case statMultiplierEvasionScore = 350
    case statMultiplierHitScore = 351
    case statMultiplierMagicalAttackScore = 352
    case statMultiplierMagicalDefenseScore = 353
    case statMultiplierMagicalHealingScore = 354
    case statMultiplierMaxHP = 355
    case statMultiplierPhysicalAttackScore = 356
    case statMultiplierPhysicalDefenseScore = 357
    case statMultiplierTrapRemovalScore = 358
    case statusInflictConfusion = 359
    case statusResistanceMultiplierConfusion = 360
    case statusResistanceMultiplierInstantDeath = 361
    case statusResistanceMultiplierPetrify = 362
    case statusResistanceMultiplierSleep = 363
    case statusResistancePercentConfusion = 364
    case tacticBarrierBreath = 365
    case tacticBarrierMagical = 366
    case tacticBarrierPhysical = 367
    case tacticBarrierGuardBreath = 368
    case tacticBarrierGuardMagical = 369
    case tacticBarrierGuardPhysical = 370
    case tacticBreathPowerAmplify = 371
    case tacticMagicPowerAmplify = 372
    case tacticSpellAmplifyBlizzard = 373
    case tacticSpellAmplifyFireball = 374
    case tacticSpellAmplifyMagicArrow = 375
    case tacticSpellAmplifyNuclear = 376
    case tacticSpellAmplifyThunderBolt = 377
    case talentStat = 378

    init?(identifier: String) {
        guard let family = Self.identifierMap[identifier] else { return nil }
        self = family
    }

    var identifier: String {
        Self.reverseMap[self] ?? ""
    }

    // MARK: - Lookup Tables

    private static let identifierMap: [String: SkillEffectFamily] = {
        var map: [String: SkillEffectFamily] = [:]
        map.reserveCapacity(378)
        for family in SkillEffectFamily.allCases {
            map[family.stringIdentifier] = family
        }
        return map
    }()

    private static let reverseMap: [SkillEffectFamily: String] = {
        var map: [SkillEffectFamily: String] = [:]
        map.reserveCapacity(378)
        for family in SkillEffectFamily.allCases {
            map[family] = family.stringIdentifier
        }
        return map
    }()

    private var stringIdentifier: String {
        switch self {
        case .absentStat: return "absent.stat"
        case .absorptionGeneral: return "absorption.general"
        case .actionOrderShuffle: return "actionOrder.shuffle"
        case .actionOrderMultiplierGeneral: return "actionOrderMultiplier.general"
        case .additionalDamageScoreAdditive: return "additionalDamageScore.additive"
        case .additionalDamageScoreMultiplier: return "additionalDamageScore.multiplier"
        case .antiHealingGeneral: return "antiHealing.general"
        case .attackCountAdditive: return "attackCount.additive"
        case .attackCountMultiplier: return "attackCount.multiplier"
        case .autoDegradationRepairGeneral: return "autoDegradationRepair.general"
        case .berserkTrigger: return "berserk.trigger"
        case .breathPower: return "breath.power"
        case .breathVariant: return "breath.variant"
        case .counterAttackEvasionMultiplierGeneral: return "counterAttackEvasionMultiplier.general"
        case .criticalDamageMultiplier: return "criticalDamageMultiplier"
        case .criticalDamagePercent: return "criticalDamagePercent"
        case .criticalDamageTakenMultiplierGeneral: return "criticalDamageTakenMultiplier.general"
        case .criticalChancePercentAdd: return "criticalChancePercent.add"
        case .criticalChancePercentCap: return "criticalChancePercent.cap"
        case .criticalChancePercentMax: return "criticalChancePercent.max"
        case .criticalChancePercentMaxDelta: return "criticalChancePercent.maxDelta"
        case .damageDealtMultiplierBreath: return "damageDealtMultiplier.breath"
        case .damageDealtMultiplierMagical: return "damageDealtMultiplier.magical"
        case .damageDealtMultiplierPhysical: return "damageDealtMultiplier.physical"
        case .damageDealtMultiplierAgainstDivine: return "damageDealtMultiplierAgainst.divine"
        case .damageDealtMultiplierAgainstDragon: return "damageDealtMultiplierAgainst.dragon"
        case .damageDealtMultiplierAgainstHumanoid: return "damageDealtMultiplierAgainst.humanoid"
        case .damageDealtMultiplierAgainstMonster: return "damageDealtMultiplierAgainst.monster"
        case .damageDealtMultiplierAgainstUndead: return "damageDealtMultiplierAgainst.undead"
        case .damageDealtPercentBreath: return "damageDealtPercent.breath"
        case .damageDealtPercentMagical: return "damageDealtPercent.magical"
        case .damageDealtPercentPhysical: return "damageDealtPercent.physical"
        case .damageTakenMultiplierBreath: return "damageTakenMultiplier.breath"
        case .damageTakenMultiplierMagical: return "damageTakenMultiplier.magical"
        case .damageTakenMultiplierPhysical: return "damageTakenMultiplier.physical"
        case .damageTakenPercentBreath: return "damageTakenPercent.breath"
        case .damageTakenPercentMagical: return "damageTakenPercent.magical"
        case .damageTakenPercentPhysical: return "damageTakenPercent.physical"
        case .degradationRepairGeneral: return "degradationRepair.general"
        case .degradationRepairBoostGeneral: return "degradationRepairBoost.general"
        case .dodgeCapGeneral: return "dodgeCap.general"
        case .endOfTurnHealingParty: return "endOfTurnHealing.party"
        case .endOfTurnSelfHPDamage: return "endOfTurnSelfHP.damage"
        case .endOfTurnSelfHPHeal: return "endOfTurnSelfHP.heal"
        case .equipmentSlotsAdditive: return "equipmentSlots.additive"
        case .equipmentSlotsMultiplier: return "equipmentSlots.multiplier"
        case .equipmentStatMultiplierArmor: return "equipmentStatMultiplier.armor"
        case .equipmentStatMultiplierBow: return "equipmentStatMultiplier.bow"
        case .equipmentStatMultiplierForSynthesis: return "equipmentStatMultiplier.for_synthesis"
        case .equipmentStatMultiplierGauntlet: return "equipmentStatMultiplier.gauntlet"
        case .equipmentStatMultiplierGem: return "equipmentStatMultiplier.gem"
        case .equipmentStatMultiplierGrimoire: return "equipmentStatMultiplier.grimoire"
        case .equipmentStatMultiplierHeavyArmor: return "equipmentStatMultiplier.heavy_armor"
        case .equipmentStatMultiplierKatana: return "equipmentStatMultiplier.katana"
        case .equipmentStatMultiplierMazoMaterial: return "equipmentStatMultiplier.mazo_material"
        case .equipmentStatMultiplierOther: return "equipmentStatMultiplier.other"
        case .equipmentStatMultiplierRaceSpecific: return "equipmentStatMultiplier.race_specific"
        case .equipmentStatMultiplierRobe: return "equipmentStatMultiplier.robe"
        case .equipmentStatMultiplierRod: return "equipmentStatMultiplier.rod"
        case .equipmentStatMultiplierShield: return "equipmentStatMultiplier.shield"
        case .equipmentStatMultiplierSword: return "equipmentStatMultiplier.sword"
        case .equipmentStatMultiplierThinSword: return "equipmentStatMultiplier.thin_sword"
        case .equipmentStatMultiplierWand: return "equipmentStatMultiplier.wand"
        case .explorationTimeMultiplierBabel: return "explorationTimeMultiplier.babel"
        case .explorationTimeMultiplierGeneral: return "explorationTimeMultiplier.general"
        case .extraActionGeneral: return "extraAction.general"
        case .growthMultiplierGeneral: return "growthMultiplier.general"
        case .incompetenceStat: return "incompetence.stat"
        case .itemStatMultiplierCriticalChancePercent: return "itemStatMultiplier.criticalChancePercent"
        case .itemStatMultiplierEvasionScore: return "itemStatMultiplier.evasionScore"
        case .itemStatMultiplierHitScore: return "itemStatMultiplier.hitScore"
        case .itemStatMultiplierMagicalAttackScore: return "itemStatMultiplier.magicalAttackScore"
        case .itemStatMultiplierMagicalDefenseScore: return "itemStatMultiplier.magicalDefenseScore"
        case .itemStatMultiplierMagicalHealingScore: return "itemStatMultiplier.magicalHealingScore"
        case .itemStatMultiplierMaxHP: return "itemStatMultiplier.maxHP"
        case .itemStatMultiplierPhysicalAttackScore: return "itemStatMultiplier.physicalAttackScore"
        case .itemStatMultiplierPhysicalDefenseScore: return "itemStatMultiplier.physicalDefenseScore"
        case .itemStatMultiplierTrapRemovalScore: return "itemStatMultiplier.trapRemovalScore"
        case .jobAssassinAccuracy: return "job.assassin.accuracy"
        case .jobAssassinCritDamage: return "job.assassin.critDamage"
        case .jobAssassinLethalBlow: return "job.assassin.lethalBlow"
        case .jobAssassinMasterAssassin: return "job.assassin.masterAssassin"
        case .jobAssassinWeakPointStrike: return "job.assassin.weakPointStrike"
        case .jobBlademasterAccuracy: return "job.blademaster.accuracy"
        case .jobBlademasterMaster: return "job.blademaster.master"
        case .jobBlademasterPeerless: return "job.blademaster.peerless"
        case .jobBlademasterPhysPower: return "job.blademaster.physPower"
        case .jobBlademasterTechnique: return "job.blademaster.technique"
        case .jobHunterAccuracy: return "job.hunter.accuracy"
        case .jobHunterBowMastery: return "job.hunter.bowMastery"
        case .jobHunterPierce: return "job.hunter.pierce"
        case .jobHunterPrecision: return "job.hunter.precision"
        case .jobHunterVolley: return "job.hunter.volley"
        case .jobJesterAllStats: return "job.jester.allStats"
        case .jobJesterConfusion: return "job.jester.confusion"
        case .jobJesterGrandFinale: return "job.jester.grandFinale"
        case .jobJesterLuck: return "job.jester.luck"
        case .jobJesterMischief: return "job.jester.mischief"
        case .jobLordCommand: return "job.lord.command"
        case .jobLordControl: return "job.lord.control"
        case .jobLordLeadership: return "job.lord.leadership"
        case .jobLordPartyPhys: return "job.lord.partyPhys"
        case .jobLordRally: return "job.lord.rally"
        case .jobMageAbsorb: return "job.mage.absorb"
        case .jobMageAmplify: return "job.mage.amplify"
        case .jobMageDestroy: return "job.mage.destroy"
        case .jobMageMagicPower: return "job.mage.magicPower"
        case .jobMageWisdom: return "job.mage.wisdom"
        case .jobMonkEnlighten: return "job.monk.enlighten"
        case .jobMonkMagicResist: return "job.monk.magicResist"
        case .jobMonkMeditate: return "job.monk.meditate"
        case .jobMonkSpirit: return "job.monk.spirit"
        case .jobMonkWard: return "job.monk.ward"
        case .jobNinjaCriticalChancePercent: return "job.ninja.criticalChancePercent"
        case .jobNinjaDeathblow: return "job.ninja.deathblow"
        case .jobNinjaEvasion: return "job.ninja.evasion"
        case .jobNinjaShadowClone: return "job.ninja.shadowClone"
        case .jobNinjaStealth: return "job.ninja.stealth"
        case .jobPriestBlessing: return "job.priest.blessing"
        case .jobPriestHealBonus: return "job.priest.healBonus"
        case .jobPriestMagicResist: return "job.priest.magicResist"
        case .jobPriestProtect: return "job.priest.protect"
        case .jobPriestSalvation: return "job.priest.salvation"
        case .jobRoyallineAllStats: return "job.royalline.allStats"
        case .jobRoyallineAura: return "job.royalline.aura"
        case .jobRoyallineDominion: return "job.royalline.dominion"
        case .jobRoyallineGpBonus: return "job.royalline.gpBonus"
        case .jobRoyallineMajesty: return "job.royalline.majesty"
        case .jobSageHealBonus: return "job.sage.healBonus"
        case .jobSageKnowledge: return "job.sage.knowledge"
        case .jobSageMagicPower: return "job.sage.magicPower"
        case .jobSageVersatile: return "job.sage.versatile"
        case .jobSageWisdom: return "job.sage.wisdom"
        case .jobSamuraiCritDamage: return "job.samurai.critDamage"
        case .jobSamuraiIai: return "job.samurai.iai"
        case .jobSamuraiKatanaMastery: return "job.samurai.katanaMastery"
        case .jobSamuraiSlash: return "job.samurai.slash"
        case .jobSamuraiSpirit: return "job.samurai.spirit"
        case .jobSpellbladeBladeMagic: return "job.spellblade.bladeMagic"
        case .jobSpellbladeFusion: return "job.spellblade.fusion"
        case .jobSpellbladeMagicPower: return "job.spellblade.magicPower"
        case .jobSpellbladeMagicSword: return "job.spellblade.magicSword"
        case .jobSpellbladePhysPower: return "job.spellblade.physPower"
        case .jobSwordsmanCombo: return "job.swordsman.combo"
        case .jobSwordsmanCounter: return "job.swordsman.counter"
        case .jobSwordsmanFollowup: return "job.swordsman.followup"
        case .jobSwordsmanMultiAttack: return "job.swordsman.multiAttack"
        case .jobSwordsmanPhysPower: return "job.swordsman.physPower"
        case .jobThiefCriticalChancePercent: return "job.thief.criticalChancePercent"
        case .jobThiefDoubleAction: return "job.thief.doubleAction"
        case .jobThiefEvasion: return "job.thief.evasion"
        case .jobThiefFortune: return "job.thief.fortune"
        case .jobThiefSurvival: return "job.thief.survival"
        case .jobWarriorArmament: return "job.warrior.armament"
        case .jobWarriorFortify: return "job.warrior.fortify"
        case .jobWarriorGuardian: return "job.warrior.guardian"
        case .jobWarriorMaxHP: return "job.warrior.maxHP"
        case .jobWarriorPhysResist: return "job.warrior.physResist"
        case .martialBonusMultiplierMartial: return "martialBonusMultiplier.martial"
        case .martialBonusPercentMartial: return "martialBonusPercent.martial"
        case .masterAssassinLethal: return "master.assassin.lethal"
        case .masterAssassinMastery: return "master.assassin.mastery"
        case .masterAssassinWeakpoint: return "master.assassin.weakpoint"
        case .masterBlademasterMaster: return "master.blademaster.master"
        case .masterBlademasterPeerless: return "master.blademaster.peerless"
        case .masterBlademasterTechnique: return "master.blademaster.technique"
        case .masterHunterPierce: return "master.hunter.pierce"
        case .masterHunterPrecision: return "master.hunter.precision"
        case .masterHunterVolley: return "master.hunter.volley"
        case .masterJesterConfusion: return "master.jester.confusion"
        case .masterJesterFinale: return "master.jester.finale"
        case .masterJesterMischief: return "master.jester.mischief"
        case .masterLordCommand: return "master.lord.command"
        case .masterLordControl: return "master.lord.control"
        case .masterLordRally: return "master.lord.rally"
        case .masterMageAbsorb: return "master.mage.absorb"
        case .masterMageAmplify: return "master.mage.amplify"
        case .masterMageDestroy: return "master.mage.destroy"
        case .masterMonkEnlighten: return "master.monk.enlighten"
        case .masterMonkMeditate: return "master.monk.meditate"
        case .masterMonkWard: return "master.monk.ward"
        case .masterNinjaDeathblow: return "master.ninja.deathblow"
        case .masterNinjaShadowClone: return "master.ninja.shadowClone"
        case .masterNinjaStealth: return "master.ninja.stealth"
        case .masterPriestBlessing: return "master.priest.blessing"
        case .masterPriestProtect: return "master.priest.protect"
        case .masterPriestSalvation: return "master.priest.salvation"
        case .masterRoyallineAura: return "master.royalline.aura"
        case .masterRoyallineDominion: return "master.royalline.dominion"
        case .masterRoyallineMajesty: return "master.royalline.majesty"
        case .masterSageKnowledge: return "master.sage.knowledge"
        case .masterSageVersatile: return "master.sage.versatile"
        case .masterSageWisdom: return "master.sage.wisdom"
        case .masterSamuraiIai: return "master.samurai.iai"
        case .masterSamuraiSlash: return "master.samurai.slash"
        case .masterSamuraiSpirit: return "master.samurai.spirit"
        case .masterSpellbladeBladeMagic: return "master.spellblade.bladeMagic"
        case .masterSpellbladeFusion: return "master.spellblade.fusion"
        case .masterSpellbladeMagicSword: return "master.spellblade.magicSword"
        case .masterSwordsmanCombo: return "master.swordsman.combo"
        case .masterSwordsmanCounter: return "master.swordsman.counter"
        case .masterSwordsmanFollowup: return "master.swordsman.followup"
        case .masterThiefDoubleAction: return "master.thief.doubleAction"
        case .masterThiefFortune: return "master.thief.fortune"
        case .masterThiefSurvival: return "master.thief.survival"
        case .masterWarriorArmament: return "master.warrior.armament"
        case .masterWarriorFortify: return "master.warrior.fortify"
        case .masterWarriorGuardian: return "master.warrior.guardian"
        case .parryGeneral: return "parry.general"
        case .partyAttackFlags: return "partyAttack.flags"
        case .partyAttackTargets: return "partyAttack.targets"
        case .penetrationDamageTakenMultiplierGeneral: return "penetrationDamageTakenMultiplier.general"
        case .procMultiplierGeneral: return "procMultiplier.general"
        case .procRateAdditiveCounter: return "procRate.additive.counter"
        case .procRateAdditiveCriticalCombo: return "procRate.additive.criticalCombo"
        case .procRateAdditiveFightingSpirit: return "procRate.additive.fightingSpirit"
        case .procRateMultiplierBreathCounter: return "procRate.multiplier.breathCounter"
        case .procRateMultiplierCounter: return "procRate.multiplier.counter"
        case .procRateMultiplierCrisisEvasion: return "procRate.multiplier.crisisEvasion"
        case .procRateMultiplierInstantResurrection: return "procRate.multiplier.instantResurrection"
        case .procRateMultiplierMagicCounter: return "procRate.multiplier.magicCounter"
        case .procRateMultiplierMagicSupport: return "procRate.multiplier.magicSupport"
        case .procRateMultiplierManaDecomposition: return "procRate.multiplier.manaDecomposition"
        case .procRateMultiplierPursuit: return "procRate.multiplier.pursuit"
        case .procRateMultiplierReattack: return "procRate.multiplier.reattack"
        case .procRateMultiplierReflectionRecovery: return "procRate.multiplier.reflectionRecovery"
        case .raceAmazonessMagicDamagedCounter: return "race.amazoness.magicDamagedCounter"
        case .raceAmazonessTurnAttackCount: return "race.amazoness.turnAttackCount"
        case .raceCyborgCumulativeHit: return "race.cyborg.cumulativeHit"
        case .raceCyborgLateAction: return "race.cyborg.lateAction"
        case .raceDarkelfAllyMagicReaction: return "race.darkelf.allyMagicReaction"
        case .raceDarkelfKillReaction: return "race.darkelf.killReaction"
        case .raceDragonnewtBreathCounter: return "race.dragonewt.breathCounter"
        case .raceDragonnewtPreemptiveBreath: return "race.dragonewt.preemptiveBreath"
        case .raceDwarfCounterAttack: return "race.dwarf.counterAttack"
        case .raceDwarfEnemyDebuff: return "race.dwarf.enemyDebuff"
        case .raceElfAutoStatusCure: return "race.elf.autoStatusCure"
        case .raceElfMagicHealReaction: return "race.elf.magicHealReaction"
        case .raceGiantCoverAlly: return "race.giant.coverAlly"
        case .raceGiantTurnHealing: return "race.giant.turnHealing"
        case .raceGnomeMagicPower: return "race.gnome.magicPower"
        case .raceGnomeSpellRecovery: return "race.gnome.spellRecovery"
        case .raceHomunculusAdditionalDamageScore: return "race.homunculus.additionalDamageScore"
        case .raceHomunculusAllStatBoost: return "race.homunculus.allStatBoost"
        case .raceHomunculusEquipSlot: return "race.homunculus.equipSlot"
        case .raceHomunculusHealBonus: return "race.homunculus.healBonus"
        case .raceHumanExpBonus: return "race.human.expBonus"
        case .raceHumanLevelDamageTaken: return "race.human.levelDamageTaken"
        case .raceHumanProcBoost: return "race.human.procBoost"
        case .raceHumanTurnBuff: return "race.human.turnBuff"
        case .raceOniNoKillReaction: return "race.oni.noKillReaction"
        case .raceOniTurnStatBuff: return "race.oni.turnStatBuff"
        case .racePsychicMagicCrit: return "race.psychic.magicCrit"
        case .racePsychicMagicNullify: return "race.psychic.magicNullify"
        case .racePygmychumBreathEvade: return "race.pygmychum.breathEvade"
        case .racePygmychumCritDamage: return "race.pygmychum.critDamage"
        case .racePygmychumExtraAction: return "race.pygmychum.extraAction"
        case .raceTenguCounterPenalty: return "race.tengu.counterPenalty"
        case .raceTenguEvasionBoost: return "race.tengu.evasionBoost"
        case .raceTenguFirstTurnAction: return "race.tengu.firstTurnAction"
        case .raceUndeadAutoResurrection: return "race.undead.autoResurrection"
        case .raceUndeadDeathSave: return "race.undead.deathSave"
        case .raceVampireMagicCounter: return "race.vampire.magicCounter"
        case .raceVampireOpeningBuff: return "race.vampire.openingBuff"
        case .raceWerecatCritCap: return "race.werecat.critCap"
        case .raceWerecatFirstTurnHit: return "race.werecat.firstTurnHit"
        case .raceWerecatTargeting: return "race.werecat.targeting"
        case .reactionCounterAllyDamagedPhysical: return "reaction.counter.allyDamagedPhysical"
        case .reactionCounterAllyDefeated: return "reaction.counter.allyDefeated"
        case .reactionCounterSelfDamagedMagical: return "reaction.counter.selfDamagedMagical"
        case .reactionCounterSelfDamagedPhysical: return "reaction.counter.selfDamagedPhysical"
        case .reactionCounterSelfEvadePhysical: return "reaction.counter.selfEvadePhysical"
        case .reactionNextTurnGeneral: return "reactionNextTurn.general"
        case .resurrectionActive: return "resurrection.active"
        case .resurrectionForced: return "resurrection.forced"
        case .resurrectionInstant: return "resurrection.instant"
        case .resurrectionNecromancer: return "resurrection.necromancer"
        case .resurrectionSave: return "resurrection.save"
        case .resurrectionUndeath: return "resurrection.undeath"
        case .resurrectionVitalized: return "resurrection.vitalized"
        case .retreatAtTurnGeneral: return "retreatAtTurn.general"
        case .rewardExperienceMultiplier: return "rewardExperience.multiplier"
        case .rewardExperiencePercent: return "rewardExperience.percent"
        case .rewardGoldMultiplier: return "rewardGold.multiplier"
        case .rewardGoldPercent: return "rewardGold.percent"
        case .rewardItemMultiplier: return "rewardItem.multiplier"
        case .rewardItemPercent: return "rewardItem.percent"
        case .rewardTitleMultiplier: return "rewardTitle.multiplier"
        case .rewardTitlePercent: return "rewardTitle.percent"
        case .rowProfileBalanced: return "rowProfile.balanced"
        case .rowProfileNear: return "rowProfile.near"
        case .rowProfileMixed: return "rowProfile.mixed"
        case .rowProfileFar: return "rowProfile.far"
        case .runawayDamage: return "runaway.damage"
        case .runawayMagic: return "runaway.magic"
        case .sacrificeRiteGeneral: return "sacrificeRite.general"
        case .shieldBlockGeneral: return "shieldBlock.general"
        case .specialAttackSpecialA: return "specialAttack.specialA"
        case .specialAttackSpecialB: return "specialAttack.specialB"
        case .specialAttackSpecialC: return "specialAttack.specialC"
        case .specialAttackSpecialD: return "specialAttack.specialD"
        case .specialAttackSpecialE: return "specialAttack.specialE"
        case .spellAccessMageForget: return "spellAccess.mage.forget"
        case .spellAccessMageLearn: return "spellAccess.mage.learn"
        case .spellAccessPriestForget: return "spellAccess.priest.forget"
        case .spellAccessPriestLearn: return "spellAccess.priest.learn"
        case .spellChargesTacticExtra: return "spellCharges.tacticExtra"
        case .spellChargesTriple: return "spellCharges.triple"
        case .spellPowerMultiplierGeneral: return "spellPowerMultiplier.general"
        case .spellPowerPercentGeneral: return "spellPowerPercent.general"
        case .spellSpecificMultiplierSpellMageBlizzard: return "spellSpecificMultiplier.spell.mage.blizzard"
        case .spellSpecificMultiplierSpellMageFireball: return "spellSpecificMultiplier.spell.mage.fireball"
        case .spellSpecificMultiplierSpellMageMagicArrow: return "spellSpecificMultiplier.spell.mage.magic_arrow"
        case .spellSpecificMultiplierSpellMageNuclear: return "spellSpecificMultiplier.spell.mage.nuclear"
        case .spellSpecificMultiplierSpellMageThunderBolt: return "spellSpecificMultiplier.spell.mage.thunder_bolt"
        case .spellSpecificMultiplierSpellPriestHeal: return "spellSpecificMultiplier.spell.priest.heal"
        case .spellSpecificMultiplierSpellPriestHealPlus: return "spellSpecificMultiplier.spell.priest.heal_plus"
        case .spellSpecificMultiplierSpellPriestPartyHeal: return "spellSpecificMultiplier.spell.priest.party_heal"
        case .spellSpecificTakenMultiplierBlizzard: return "spellSpecificTakenMultiplier.blizzard"
        case .spellSpecificTakenMultiplierFireball: return "spellSpecificTakenMultiplier.fireball"
        case .spellSpecificTakenMultiplierMagicArrow: return "spellSpecificTakenMultiplier.magic_arrow"
        case .spellSpecificTakenMultiplierNuclear: return "spellSpecificTakenMultiplier.nuclear"
        case .spellSpecificTakenMultiplierThunderBolt: return "spellSpecificTakenMultiplier.thunder_bolt"
        case .spellTierUnlockMage: return "spellTierUnlock.mage"
        case .spellTierUnlockPriest: return "spellTierUnlock.priest"
        case .statAdditiveEvasionScore: return "statAdditive.evasionScore"
        case .statAdditiveHitScore: return "statAdditive.hitScore"
        case .statAdditiveMagicalAttackScore: return "statAdditive.magicalAttackScore"
        case .statAdditiveMagicalDefenseScore: return "statAdditive.magicalDefenseScore"
        case .statAdditiveMagicalHealingScore: return "statAdditive.magicalHealingScore"
        case .statAdditivePhysicalAttackScore: return "statAdditive.physicalAttackScore"
        case .statAdditivePhysicalDefenseScore: return "statAdditive.physicalDefenseScore"
        case .statConversionLinearAttackCountCriticalChancePercent: return "statConversionLinear.attackCount.criticalChancePercent"
        case .statConversionLinearAttackCountEvasionScore: return "statConversionLinear.attackCount.evasionScore"
        case .statConversionLinearAttackCountMagicalAttackScore: return "statConversionLinear.attackCount.magicalAttackScore"
        case .statConversionLinearAttackCountMagicalDefenseScore: return "statConversionLinear.attackCount.magicalDefenseScore"
        case .statConversionLinearAttackCountMagicalHealingScore: return "statConversionLinear.attackCount.magicalHealingScore"
        case .statConversionLinearAttackCountPhysicalDefenseScore: return "statConversionLinear.attackCount.physicalDefenseScore"
        case .statConversionPercentMagicalAttackScoreHitScore: return "statConversionPercent.magicalAttackScore.hitScore"
        case .statConversionPercentMagicalAttackScoreMaxHP: return "statConversionPercent.magicalAttackScore.maxHP"
        case .statConversionPercentMagicalAttackScorePhysicalAttackScore: return "statConversionPercent.magicalAttackScore.physicalAttackScore"
        case .statConversionPercentMagicalHealingScoreHitScore: return "statConversionPercent.magicalHealingScore.hitScore"
        case .statConversionPercentMagicalHealingScoreMagicalAttackScore: return "statConversionPercent.magicalHealingScore.magicalAttackScore"
        case .statConversionPercentMagicalHealingScoreMagicalDefenseScore: return "statConversionPercent.magicalHealingScore.magicalDefenseScore"
        case .statConversionPercentMagicalHealingScoreMaxHP: return "statConversionPercent.magicalHealingScore.maxHP"
        case .statConversionPercentMagicalHealingScorePhysicalAttackScore: return "statConversionPercent.magicalHealingScore.physicalAttackScore"
        case .statConversionPercentPhysicalAttackScoreMaxHP: return "statConversionPercent.physicalAttackScore.maxHP"
        case .statConversionPercentPhysicalDefenseScoreAttackAndHit: return "statConversionPercent.physicalDefenseScore.attackAndHit"
        case .statConversionPercentPhysicalDefenseScoreMaxHP: return "statConversionPercent.physicalDefenseScore.maxHP"
        case .statMultiplierEvasionScore: return "statMultiplier.evasionScore"
        case .statMultiplierHitScore: return "statMultiplier.hitScore"
        case .statMultiplierMagicalAttackScore: return "statMultiplier.magicalAttackScore"
        case .statMultiplierMagicalDefenseScore: return "statMultiplier.magicalDefenseScore"
        case .statMultiplierMagicalHealingScore: return "statMultiplier.magicalHealingScore"
        case .statMultiplierMaxHP: return "statMultiplier.maxHP"
        case .statMultiplierPhysicalAttackScore: return "statMultiplier.physicalAttackScore"
        case .statMultiplierPhysicalDefenseScore: return "statMultiplier.physicalDefenseScore"
        case .statMultiplierTrapRemovalScore: return "statMultiplier.trapRemovalScore"
        case .statusInflictConfusion: return "status.inflict.confusion"
        case .statusResistanceMultiplierConfusion: return "statusResistanceMultiplier.confusion"
        case .statusResistanceMultiplierInstantDeath: return "statusResistanceMultiplier.instantDeath"
        case .statusResistanceMultiplierPetrify: return "statusResistanceMultiplier.petrify"
        case .statusResistanceMultiplierSleep: return "statusResistanceMultiplier.sleep"
        case .statusResistancePercentConfusion: return "statusResistancePercent.confusion"
        case .tacticBarrierBreath: return "tacticBarrier.breath"
        case .tacticBarrierMagical: return "tacticBarrier.magical"
        case .tacticBarrierPhysical: return "tacticBarrier.physical"
        case .tacticBarrierGuardBreath: return "tacticBarrierGuard.breath"
        case .tacticBarrierGuardMagical: return "tacticBarrierGuard.magical"
        case .tacticBarrierGuardPhysical: return "tacticBarrierGuard.physical"
        case .tacticBreathPowerAmplify: return "tacticBreathPowerAmplify"
        case .tacticMagicPowerAmplify: return "tacticMagicPowerAmplify"
        case .tacticSpellAmplifyBlizzard: return "tacticSpellAmplify.blizzard"
        case .tacticSpellAmplifyFireball: return "tacticSpellAmplify.fireball"
        case .tacticSpellAmplifyMagicArrow: return "tacticSpellAmplify.magic_arrow"
        case .tacticSpellAmplifyNuclear: return "tacticSpellAmplify.nuclear"
        case .tacticSpellAmplifyThunderBolt: return "tacticSpellAmplify.thunder_bolt"
        case .talentStat: return "talent.stat"
        }
    }
}
